[ { TYPE: 'KEY_WORD_CLASS', position: 0, lexem: 'class' },
  { TYPE: 'SPACE', position: 5, lexem: ' ' },
  { TYPE: 'ID', position: 6, lexem: 'main' },
  { TYPE: 'SPACE', position: 10, lexem: ' ' },
  { TYPE: 'OPEN_BRACE', position: 11, lexem: '{' },
  { TYPE: 'NEW_LINE', position: 12, lexem: '\n' },
  { TYPE: 'SPACE', position: 13, lexem: ' ' },
  { TYPE: 'SPACE', position: 14, lexem: ' ' },
  { TYPE: 'SPACE', position: 15, lexem: ' ' },
  { TYPE: 'SPACE', position: 16, lexem: ' ' },
  { TYPE: 'KEY_WORD_VAR', position: 17, lexem: 'var' },
  { TYPE: 'SPACE', position: 20, lexem: ' ' },
  { TYPE: 'ID', position: 21, lexem: 'j' },
  { TYPE: 'SPACE', position: 22, lexem: ' ' },
  { TYPE: 'OPERATOR_ASSIGN', position: 23, lexem: '=' },
  { TYPE: 'SPACE', position: 24, lexem: ' ' },
  { TYPE: 'INT', position: 25, lexem: '30' },
  { TYPE: 'SEMI_COLON', position: 27, lexem: ';' },
  { TYPE: 'NEW_LINE', position: 28, lexem: '\n' },
  { TYPE: 'SPACE', position: 29, lexem: ' ' },
  { TYPE: 'SPACE', position: 30, lexem: ' ' },
  { TYPE: 'SPACE', position: 31, lexem: ' ' },
  { TYPE: 'SPACE', position: 32, lexem: ' ' },
  { TYPE: 'KEY_WORD_RETURN', position: 33, lexem: 'return' },
  { TYPE: 'SPACE', position: 39, lexem: ' ' },
  { TYPE: 'ID', position: 40, lexem: 'j' },
  { TYPE: 'SEMI_COLON', position: 41, lexem: ';' },
  { TYPE: 'NEW_LINE', position: 42, lexem: '\n' },
  { TYPE: 'CLOSE_BRACE', position: 43, lexem: '}' } ]