[ { TYPE: 'KEY_WORD_CLASS', position: 0, lexem: 'class' },
  { TYPE: 'SPACE', position: 5, lexem: ' ' },
  { TYPE: 'ID', position: 6, lexem: 'main' },
  { TYPE: 'SPACE', position: 10, lexem: ' ' },
  { TYPE: 'OPEN_BRACE', position: 11, lexem: '{' },
  { TYPE: 'NEW_LINE', position: 12, lexem: '\n' },
  { TYPE: 'SPACE', position: 13, lexem: ' ' },
  { TYPE: 'SPACE', position: 14, lexem: ' ' },
  { TYPE: 'SPACE', position: 15, lexem: ' ' },
  { TYPE: 'SPACE', position: 16, lexem: ' ' },
  { TYPE: 'KEY_WORD_VAR', position: 17, lexem: 'var' },
  { TYPE: 'SPACE', position: 20, lexem: ' ' },
  { TYPE: 'ID', position: 21, lexem: 'lol' },
  { TYPE: 'SPACE', position: 24, lexem: ' ' },
  { TYPE: 'OPERATOR_ASSIGN', position: 25, lexem: '=' },
  { TYPE: 'SPACE', position: 26, lexem: ' ' },
  { TYPE: 'INT', position: 27, lexem: '50' },
  { TYPE: 'SEMI_COLON', position: 29, lexem: ';' },
  { TYPE: 'NEW_LINE', position: 30, lexem: '\n' },
  { TYPE: 'SPACE', position: 31, lexem: ' ' },
  { TYPE: 'SPACE', position: 32, lexem: ' ' },
  { TYPE: 'SPACE', position: 33, lexem: ' ' },
  { TYPE: 'SPACE', position: 34, lexem: ' ' },
  { TYPE: 'KEY_WORD_RETURN', position: 35, lexem: 'return' },
  { TYPE: 'SPACE', position: 41, lexem: ' ' },
  { TYPE: 'ID', position: 42, lexem: 'j' },
  { TYPE: 'SEMI_COLON', position: 43, lexem: ';' },
  { TYPE: 'NEW_LINE', position: 44, lexem: '\n' },
  { TYPE: 'CLOSE_BRACE', position: 45, lexem: '}' } ]